language: go
go:
- 1.9.2
before_install:
- curl -Ls https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > ngrok.zip
- unzip ngrok.zip
- rm ngrok.zip
- export PATH=$(pwd):$PATH
install:
- make depend
script:
- make all
