[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/cenk/backoff"
  version = "1.1.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-4.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.7"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.7"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.7"

[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"
